-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- #######################################################################################
--  > SSSystem
-- #######################################################################################

-- Refer to the wiki for more information.
-- https://wiki.hyprland.org/Configuring/

--###########
--## Init ###
--###########

hl.exec_cmd("/home/" .. os.getenv("USER") .. "/.config/hypr/scripts/enshure-wal.sh")

local color_config_path = "/home/" .. os.getenv("USER") .. "/.cache/wal/colors-hyprland.lua"
local hyprpaper_config_path = "/home/" .. os.getenv("USER") .. "/.cache/wal/hyprpaper.conf"
local scripts = "/home/" .. os.getenv("USER") .. "/.config/hypr/scripts"

-- load pywal generated color config
require(color_config_path)


--###############
--## MONITORS ###
--###############

-- See https://wiki.hyprland.org/Configuring/Monitors/
-- monitor=name,resolution,position,scale
-- (position := grid position from top left corner)
-- use this command to see all monitors: hyprctl monitors all

local monitor1 = "DP-2"
local monitor2 = "DP-3"

hl.monitor({
    output   = monitor1,
    mode     = "2560x1440",
    position = "0x0",
    scale    = 1,
    vrr = 0,
})

hl.monitor({
    output   = monitor2,
    mode     = "1920x1080",
    position = "-1920x300",
    scale    = 1,
    vrr = 0,
})

-- All other montors mirror monitor1
hl.monitor({
    output   = "",
    mode     = "preferred",
    position = "auto",
    scale    = 1,
    mirror = "DP-2",
})

-- hl.monitor({
--     output   = "",
--     mode     = "preferred",
--     position = "auto",
--     scale    = 1,
-- })

-- Default workspace setup

--#################
--## WORKSPACES ###
--#################
hl.workspace_rule({
    workspace = 1,
    monitor = "DP-2",
    default = true,
    persistent = true,
})

hl.workspace_rule({
    workspace = 2,
    monitor = "DP-2",
    default = false,
})

hl.workspace_rule({
    workspace = 10,
    monitor = "DP-3",
    default = true,
    persistent = false,
})

hl.workspace_rule({
    workspace = 9,
    monitor = "DP-3",
    default = true,
})

--##################
--## MY PROGRAMS ###
--##################

-- See https://wiki.hyprland.org/Configuring/Keywords/
-- Set programs that you use

local terminal = "kitty"
local fileManager = "dolphin"
local menu = "rofi -modi drun,window,keys"
local menu_launcher = "rofi -modi drun,window,keys -show drun"
local menu_window = "rofi -modi drun,window,keys -show window"
local menu_emoji = "rofi -modi emoji:rofimoji --action copy --files emojis,nerd:rofimoji --action copy --files nerd_font -show emoji"

--##################
--## Layer Rules ###
--##################

hl.layer_rule({
    match = {
        namespace = "rofi",
    },
    blur = true,
    xray = 1,
    blur_popups = true,
    ignore_alpha = 0,
})

-- swaync (notification center)
hl.layer_rule({
    match = {
        namespace = "swaync-control-center",
    },
    blur = true,
    ignore_alpha = 0.5,
})

hl.layer_rule({
    match = {
        namespace = "swaync-notification-window",
    },
    blur = true,
    ignore_alpha = 0.5,
})

--###############################
--## Application Window Rules ###
--###############################

--## Startup Applications
hl.window_rule({
    name  = "discord_rules",
    match = {
        class = "^(discord)$",
    },
    workspace = 10,
})

hl.window_rule({
    name  = "spotify_rules",
    match = {
        class = "^(spotify)$",
    },
    workspace = 10,
})

--## Steam
hl.window_rule({
    name  = "steam_rules",
    match = {
        class = "^(steam)$",
    },
    workspace = 9,
})

hl.window_rule({
    name  = "steam_app_rules",
    match = {
        class = "^(steam_app_).*$",
    },
    fullscreen = true,
    monitor = "DP-2",
})

hl.window_rule({
    name  = "trackmania_rules",
    match = {
        class = "^(trackmania).*$",
    },
    monitor = "DP-2",
})

hl.window_rule({
    name  = "fullscreen_rules",
    match = {
        class = ".*",
    },
    idle_inhibit = "fullscreen",
    suppress_event = "maximize",
})

--## Other Applications
hl.window_rule({
    name  = "dolphin_rules",
    match = {
        class = "^(org.kde.dolphin)$",
    },
    float = true,
    center = true,
    size = { "(monitor_w*0.4)", "(monitor_h*0.5)" },
    scroll_mouse = 2.0,
})

hl.window_rule({
    name  = "dolphin_copy_paste_window_rules",
    match = {
        class = "^(org.kde.dolphin)$",
        title = "^(Copying — Dolphin)$",
    },
    no_initial_focus = true,
    float = true,
})

hl.window_rule({
    name  = "pwvucontrol_rules",
    match = {
        class = "^(com.saivert.pwvucontrol)$",
    },
    float = true,
})

hl.window_rule({
    name  = "nmce_rules",
    match = {
        class = "^(nm-connection-editor)$",
    },
    float = true,
})

hl.window_rule({
    name  = "1password_rules",
    match = {
        class = "^(1password)$",
    },
    float = true,
})

hl.window_rule({
    name  = "ark_rules",
    match = {
        class = "^(org.kde.ark)$",
    },
    float = true,
})

hl.window_rule({
    name  = "qview_rules",
    match = {
        class = "^(com.interversehq.qView)$",
    },
    float = true,
    opacity = "1 override 1 override",
})

hl.window_rule({
    name  = "pureref_rules",
    match = {
        class = "^(PureRef)$",
    },
    float = true,
    opacity = "1 override 1 override",
})

hl.window_rule({
    name  = "firefox_rules",
    match = {
        class = "^(firefox)$",
    },
    opacity = "1 override 1 override",
})

hl.window_rule({
    name  = "chromium_rules",
    match = {
        class = "^(chromium)$",
    },
    opacity = "1 override 1 override",
})

hl.window_rule({
    name  = "beeref_rules",
    match = {
        class = "^(python3)$",
        title = "^(.*BeeRef)$",
    },
    float = true,
    opacity = "1 override 1 override",
})

hl.window_rule({
    name  = "mpv_rules",
    match = {
        class = "^(mpv)$",
    },
    float = true,
    opacity = "1 override 1 override",
})

hl.window_rule({
    name  = "zen_rules",
    match = {
        class = "^(zen)$",
    },
    float = true,
    opacity = "1 override 1 override",
})

hl.window_rule({
    name  = "krita_rules",
    match = {
        class = "^(krita)$",
    },
    opacity = "1 override 1 override",
})

-- Fix some dragging issues with XWayland
hl.window_rule({
    name  = "dragging_issue_fix_rules",
    match = {
        class = "^$",
        title = "^$",
        xwayland = 1,
        float = 1,
        fullscreen = 0,
        pin = 0,
    },
    no_focus = true,
})

--################
--## AUTOSTART ###
--################

-- My startup applications
hl.on("hyprland.start", function () 
  hl.exec_cmd("flatpak run org.mozilla.thunderbird_esr", { workspace = "1 silent" })
  hl.exec_cmd("spotify-launcher", { workspace = "10 silent"})
  hl.exec_cmd("discord", { workspace = "10 silent"})
end)


-- Autostart necessary processes (like notifications daemons, status bars, etc.)
-- Or execute your favorite apps at launch like this:
hl.on("hyprland.start", function () 
  hl.exec_cmd("systemctl --user start hyprpolkitagent")
  hl.exec_cmd("hyprpaper -c ".. hyprpaper_config_path .." &")
  hl.exec_cmd("wl-paste --watch cliphist store")
  hl.exec_cmd("waybar &")
  --hl.exec_cmd("hypridle &") --broken?
  hl.exec_cmd("swaync")
  hl.exec_cmd("swaync-cient -df")
  hl.exec_cmd("hyprswitch init --show-title --size-factor 5.5 --workspaces-per-row 5 &")
end)

--############################
--## ENVIRONMENT VARIABLES ###
--############################

-- See https://wiki.hyprland.org/Configuring/Environment-variables/

hl.env("XCURSOR_SIZE", 30)
hl.env("HYPRCURSOR_SIZE", 30)
hl.env("HYPRCURSOR_THEME", "rose-pine-hyprcursor")

-- env = QT_QPA_PLATFORMTHEME,gtk3
-- KDE dolphin theme
-- env = QT_QPA_PLATFORM,wayland

hl.env("QT_QPA_PLATFORMTHEME", "kde")
hl.env("QT_STYLE_OVERRIDE", "kvantum")

-- env = QT_QPA_PLATFORMTHEME,qt5ct
-- sudo pacman -S kvantum
-- sudo pacman -S materia-kde kvantum-theme-materia

-- Electron platform hint
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "auto")

-- Nvidia shit:
hl.env("LIBVA_DRIVER_NAME", "nvidia")
hl.env("__GLX_VENDOR_LIBRARY_NAME", "nvidia")
hl.env("__GL_VRR_ALLOWED", 0)
hl.env("GMB_BACKEND", "nvidia-drm")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("NVD_BACKEND", "direct")

--####################
--## LOOK AND FEEL ###
--####################
-- Refer to https://wiki.hyprland.org/Configuring/Variables/
-- https://wiki.hyprland.org/Configuring/Variables/#general

hl.config({
    general = {
        gaps_in = 3,
        gaps_out = 10,
        border_size = 2,
        -- https://wiki.hyprland.org/Configuring/Variables/#variable-types for info about colors
        -- Set to true enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = false,
        -- Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
        allow_tearing = false,
        layout = "dwindle",
        col = {
            active_border = { colors = { color5, color1 }, angle = 45 },
            inactive_border = color2_50,
        },
    },
})

hl.config({
    group = {
        groupbar = {
            enabled = true,
            gradients = true,
            col = {
                active = color5,
                inactive = color2_70,
                locked_active = color5_50,
                locked_inactive = color2_40,
            },
            font_family = "JetBrainsMonoNL Nerd Font Mono",
            font_size = 12,
            height = 20,
            indicator_height = 20,
            render_titles = true,
            gradients = false,
            rounding = 5,
        },
        col = {
            border_active = { colors = { color5, color1 }, angle = 45 },
            border_inactive = color2_50,
        },
    },
})

-- https://wiki.hyprland.org/Configuring/Variables/#decoration

hl.config({
    decoration = {
        rounding = 5,
        active_opacity = 1,
        inactive_opacity = 0.8,
        fullscreen_opacity = 1,
        blur = {
            enabled = true,
            size = 3,
            passes = 5,
            new_optimizations = true,
            ignore_opacity = true,
            xray = false,
            popups = true,
            contrast = 1.2,
            brightness = 1,
        },
        shadow = {
            enabled = true,
            range = 15,
            render_power = 5,
            color = background_50,
        },
    },
})

-- https://wiki.hyprland.org/Configuring/Variables/#animations
hl.config({
    animations = {
        enabled = true,
        -- Default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more
    },
})

-- See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
hl.config({
    dwindle = {
        preserve_split = true,
        -- You probably want this
    },
})

-- See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
hl.config({
    master = {
        new_status = "master",
    },
})

-- https://wiki.hyprland.org/Configuring/Variables/#misc
hl.config({
    misc = {
        vrr = 0,
        force_default_wallpaper = 1,
        -- -1 # Set to 0 or 1 to disable the anime mascot wallpapers
        disable_hyprland_logo = true,
        -- If true disables the random hyprland logo / anime girl background. :(
        initial_workspace_tracking = 2,
        -- 0 - disabled, 1 - single-shot, 2 - persistent (all children too)
    },
})

--############
--## INPUT ###
--############

-- https://wiki.hyprland.org/Configuring/Variables/#input
hl.config({
    input = {
        kb_layout = "de",
        follow_mouse = 1,
        sensitivity = 0,
        -- -1.0 - 1.0, 0 means no modification.
        scroll_factor = 1.0,
        touchpad = {
            natural_scroll = false,
        },
        tablet = {
            --output = current
            output = "DP-2",
        },
    },
})

hl.config({
    cursor = {
        no_break_fs_vrr = 0,
    },
})

-- https://wiki.hyprland.org/Configuring/Variables/#gestures
hl.config({
    gestures = {
        workspace_swipe_touch = false,
    },
})

-- Example per-device config

-- See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more

hl.device({
    name = "epic-mouse-v1",
    sensitivity = -0.5,
})

--##################
--## KEYBINDINGS ###
--##################

-- See https://wiki.hyprland.org/Configuring/Keywords/
local mainMod = "SUPER"

-- Sets "Windows" key as main modifier
-- Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
-- bind = $mainMod, RETURN, exec, $terminal

hl.bind(mainMod .. " + " .. "Q", hl.dsp.window.close())
hl.bind(mainMod .. " + " .. "L", hl.dsp.exec_cmd("hyprlock"))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "M", hl.dsp.exit())
hl.bind("CTRL + ALT" .. " + " .. "Escape", hl.dsp.exit())
hl.bind(mainMod .. " + " .. "D", hl.dsp.window.float())
hl.bind(mainMod .. " + " .. "RETURN", hl.dsp.window.fullscreen())
hl.bind(mainMod .. " + " .. "R", hl.dsp.exec_cmd("rofi -modi drun,window,keys -show drun"))
hl.bind(mainMod .. " + " .. "PERIOD", hl.dsp.exec_cmd("rofi -modi emoji:rofimoji --action copy --files emojis,nerd:rofimoji --action copy --files nerd_font -show emoji"))
hl.bind(mainMod .. " + " .. "O", hl.dsp.window.pseudo()) -- dwindle
-- bind = $mainMod, J, togglesplit, -- dwindle
hl.bind(mainMod .. " + " .. "J", hl.dsp.layout("togglesplit"))
hl.bind(mainMod .. " + " .. "F", hl.dsp.exec_cmd("firefox"))
hl.bind(mainMod .. " + " .. "Z", hl.dsp.exec_cmd("zen-browser"))

-- Programs
hl.bind(mainMod .. " + " .. "T", hl.dsp.exec_cmd("kitty"))
hl.bind(mainMod .. " + " .. "E", hl.dsp.exec_cmd("dolphin && XDG_MENU_PREFIX=arch- kbuildsycoca6"))
hl.bind(mainMod .. " + " .. "Y", hl.dsp.exec_cmd("kitty -e yazi"))
hl.bind(mainMod .. " + " .. "B", hl.dsp.exec_cmd("firefox"))
hl.bind(mainMod .. " + " .. "K", hl.dsp.exec_cmd("flatpak run org.kde.krita"))

-- Hyprswitch

local hyprswitch_key = "TAB"
hl.bind(mainMod .. " + " .. hyprswitch_key, hl.dsp.exec_cmd("hyprswitch gui --mod-key super --key tab --max-switch-offset 9 --hide-active-window-border"))
--bind = $mainMod, TAB, exec, $menu_window

-- Scripts
hl.bind(mainMod .. " + " .. "V", hl.dsp.exec_cmd("/home/" .. os.getenv("USER") .. "/.config/hypr/scripts/clip-manager.sh")) -- Clipboard Manager

-- Snipping tool
hl.bind("PRINT", hl.dsp.exec_cmd("hyprshot -m output -o ~/Pictures/Screenshots"))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "S", hl.dsp.exec_cmd("hyprshot -m region -z --clipboard-only"))

-- Move focus with mainMod + arrow keys
hl.bind(mainMod .. " + " .. "left", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + " .. "right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + " .. "up", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + " .. "down", hl.dsp.focus({ direction = "down" }))

-- Move workspace
hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "right", hl.dsp.focus({ workspace = "r+1" }))
hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "left", hl.dsp.focus({ workspace = "r-1" }))

-- Move window to workspace
hl.bind(mainMod .. " + " .. "SHIFT + CTRL" .. " + " .. "right", hl.dsp.window.move({ workspace = "r+1" }))
hl.bind(mainMod .. " + " .. "SHIFT + CTRL" .. " + " .. "left", hl.dsp.window.move({ workspace = "r-1" }))

-- Move window
hl.bind(mainMod .. " + SHIFT + Left", hl.dsp.window.move({ direction = "left" }))
hl.bind(mainMod .. " + SHIFT + Right", hl.dsp.window.move({ direction = "right" }))
hl.bind(mainMod .. " + SHIFT + Up", hl.dsp.window.move({ direction = "up" }))
hl.bind(mainMod .. " + SHIFT + Down", hl.dsp.window.move({ direction = "down" }))

-- Resize window
-- bind = $mainMod ALT, Right, resizeactive, 50 0
-- bind = $mainMod ALT, Left, resizeactive, -50 0
-- bind = $mainMod ALT, Up, resizeactive, 0 -50
-- bind = $mainMod ALT, Down, resizeactive, 0 50

-- groups
hl.bind(mainMod .. " + " .. "G", hl.dsp.group.next({ forward = false }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "G", hl.dsp.group.toggle())

-- Switch workspaces with mainMod + [0-9]
hl.bind(mainMod .. " + " .. 1, hl.dsp.focus({ workspace = 1 }))
hl.bind(mainMod .. " + " .. 2, hl.dsp.focus({ workspace = 2 }))
hl.bind(mainMod .. " + " .. 3, hl.dsp.focus({ workspace = 3 }))
hl.bind(mainMod .. " + " .. 4, hl.dsp.focus({ workspace = 4 }))
hl.bind(mainMod .. " + " .. 5, hl.dsp.focus({ workspace = 5 }))
hl.bind(mainMod .. " + " .. 6, hl.dsp.focus({ workspace = 6 }))
hl.bind(mainMod .. " + " .. 7, hl.dsp.focus({ workspace = 7 }))
hl.bind(mainMod .. " + " .. 8, hl.dsp.focus({ workspace = 8 }))
hl.bind(mainMod .. " + " .. 9, hl.dsp.focus({ workspace = 9 }))
hl.bind(mainMod .. " + " .. 0, hl.dsp.focus({ workspace = 10 }))

-- Move active window to a workspace with mainMod + SHIFT + [0-9]
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 1, hl.dsp.window.move({ workspace = 1 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 2, hl.dsp.window.move({ workspace = 2 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 3, hl.dsp.window.move({ workspace = 3 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 4, hl.dsp.window.move({ workspace = 4 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 5, hl.dsp.window.move({ workspace = 5 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 6, hl.dsp.window.move({ workspace = 6 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 7, hl.dsp.window.move({ workspace = 7 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 8, hl.dsp.window.move({ workspace = 8 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 9, hl.dsp.window.move({ workspace = 9 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 0, hl.dsp.window.move({ workspace = 10 }))

-- Example special workspace (scratchpad)
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "F", hl.dsp.window.fullscreen())
-- bind = $mainMod, O, exec, $scripts/magic-workspace-toggle.sh
-- bind = $mainMod SHIFT, O, togglespecialworkspace, magic

-- Scroll through existing workspaces with mainMod + scroll
hl.bind(mainMod .. " + " .. "mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + " .. "mouse_up", hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + " .. "mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind(mainMod .. " + " .. "mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Mouse volume control (R.A.T. 7)
-- (check with 'wev' command what the buttons are)
hl.bind("mouse:278", hl.dsp.exec_cmd("pamixer -d 5"), { locked = true })
hl.bind("mouse:277", hl.dsp.exec_cmd("pamixer -i 5"), { locked = true })

-- Laptop multimedia keys for volume and LCD brightness
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { locked = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true })
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), { locked = true })
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl s 10%+"), { locked = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl s 10%-"), { locked = true })

-- Requires playerctl
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })


-- Exec (run every reload)
hl.on("config.reloaded", function()
    -- Fix dolphin open with issue
    -- https://www.lorenzobettini.it/2024/05/fixing-the-empty-open-with-in-dolphin-in-hyprland/
    hl.exec_cmd("XDG_MENU_PREFIX=arch- kbuildsycoca6")
end)
